#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════
# SOSphere — Release APK signing helper
# ─────────────────────────────────────────────────────────────────────────
# One-time setup: generate the release keystore + save secrets locally so
# `gradlew assembleRelease` produces a properly-signed APK/AAB. A release-
# signed APK is what unlocks biometric fingerprint on Realme (ColorOS),
# Xiaomi (MIUI), and Huawei (HarmonyOS) devices — debug-signed APKs get
# blocked by those OEMs' biometric subsystems.
#
# RUN THIS ONCE per project. The keystore it produces is your SINGLE
# identity on Google Play — BACK IT UP to at least two secure locations.
#
# What this script does:
#   1. Checks that JDK `keytool` is available.
#   2. Generates a 2048-bit RSA keystore valid for 30 years.
#   3. Writes android/app/keystore.properties pointing at the new file.
#   4. Reminds you what to back up.
#
# What it does NOT do:
#   • It doesn't upload anything anywhere.
#   • It doesn't email you the password (you pick it, you keep it).
#   • It doesn't commit anything to git (keystore + properties are
#     gitignored; .example template is what's tracked).
# ═══════════════════════════════════════════════════════════════════════════

set -euo pipefail

cd "$(dirname "$0")/.."
ROOT="$(pwd)"
KEYSTORE_DIR="$ROOT/android/app"
KEYSTORE_PATH="$KEYSTORE_DIR/sosphere-release.jks"
PROPS_PATH="$KEYSTORE_DIR/keystore.properties"

echo ""
echo "════════════════════════════════════════════════════════════════════"
echo "  SOSphere — Release Keystore Generator"
echo "════════════════════════════════════════════════════════════════════"
echo ""

# 1. Check for keytool
if ! command -v keytool >/dev/null 2>&1; then
    echo "✖  keytool not found. Install JDK 17 and re-run."
    echo "   macOS:    brew install openjdk@17"
    echo "   Windows:  choco install temurin17"
    echo "   Linux:    apt-get install openjdk-17-jdk"
    exit 1
fi

# 2. Refuse to overwrite an existing keystore (destroying it is irrecoverable)
if [ -f "$KEYSTORE_PATH" ]; then
    echo "⚠  A keystore already exists at:"
    echo "     $KEYSTORE_PATH"
    echo ""
    echo "   Overwriting it would permanently lock you out of updating the"
    echo "   app on Google Play. If you really want a fresh keystore:"
    echo "     1. BACK UP the existing one first."
    echo "     2. Delete it manually."
    echo "     3. Re-run this script."
    exit 1
fi

# 3. Prompt for keystore password (twice, matching)
echo "You'll be asked to create a password for the keystore."
echo "Rules: 8+ characters, use a password manager, write it down securely."
echo ""

read -r -s -p "Keystore password: " KS_PASS
echo ""
read -r -s -p "Confirm password:   " KS_PASS_CONFIRM
echo ""

if [ "$KS_PASS" != "$KS_PASS_CONFIRM" ]; then
    echo "✖  Passwords do not match. Aborting."
    exit 1
fi
if [ ${#KS_PASS} -lt 8 ]; then
    echo "✖  Password must be at least 8 characters. Aborting."
    exit 1
fi

# 4. Distinguished Name fields — pulled from env if set, prompt otherwise
CN="${SOSPHERE_CERT_CN:-SOSphere Safety Platform}"
O="${SOSPHERE_CERT_O:-SOSphere}"
OU="${SOSPHERE_CERT_OU:-Mobile}"
L="${SOSPHERE_CERT_L:-Riyadh}"
ST="${SOSPHERE_CERT_ST:-Riyadh}"
C="${SOSPHERE_CERT_C:-SA}"
ALIAS="sosphere"

echo ""
echo "Certificate details (press Enter to accept defaults):"
read -r -p "  Common Name [$CN]: " input; CN="${input:-$CN}"
read -r -p "  Organization [$O]: " input; O="${input:-$O}"
read -r -p "  Country [$C]: " input; C="${input:-$C}"

# 5. Generate the keystore.
mkdir -p "$KEYSTORE_DIR"
keytool -genkeypair \
    -v \
    -keystore "$KEYSTORE_PATH" \
    -alias "$ALIAS" \
    -keyalg RSA \
    -keysize 2048 \
    -validity 10950 \
    -storetype JKS \
    -storepass "$KS_PASS" \
    -keypass "$KS_PASS" \
    -dname "CN=$CN, OU=$OU, O=$O, L=$L, ST=$ST, C=$C"

echo ""
echo "✓  Keystore generated: $KEYSTORE_PATH"

# 6. Write keystore.properties for gradle
cat > "$PROPS_PATH" <<EOF
# SOSphere release signing — generated by scripts/release-signing.sh
# DO NOT COMMIT. This file is already gitignored.
storeFile=sosphere-release.jks
storePassword=$KS_PASS
keyAlias=$ALIAS
keyPassword=$KS_PASS
EOF
chmod 600 "$PROPS_PATH" 2>/dev/null || true

echo "✓  keystore.properties written: $PROPS_PATH"
echo ""
echo "════════════════════════════════════════════════════════════════════"
echo "  BACK UP NOW — this is a one-chance thing"
echo "════════════════════════════════════════════════════════════════════"
echo ""
echo "  1. Copy $KEYSTORE_PATH to:"
echo "       • A password manager vault attachment (1Password / Bitwarden)"
echo "       • An encrypted offline drive"
echo "       • A trusted cloud drive with 2FA enabled"
echo ""
echo "  2. Write the password down separately from the file."
echo ""
echo "  3. If you lose this file OR forget this password, you will NEVER"
echo "     be able to update the app on Google Play. A new keystore means"
echo "     a new package identity = users have to uninstall + reinstall."
echo ""
echo "════════════════════════════════════════════════════════════════════"
echo "  Build a signed release APK now:"
echo "     cd android && ./gradlew assembleRelease"
echo ""
echo "  Build an Android App Bundle for Play Store upload:"
echo "     cd android && ./gradlew bundleRelease"
echo "════════════════════════════════════════════════════════════════════"
