# ===========================================================================
# SOSphere - Release APK signing helper (Windows PowerShell)
# ---------------------------------------------------------------------------
# Mirror of scripts/release-signing.sh for native Windows (PowerShell).
# Run once to generate the release keystore + keystore.properties locally.
# Release-signed APKs unlock fingerprint biometric on Realme/Xiaomi/Huawei.
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File scripts\release-signing.ps1
# ===========================================================================

$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
Set-Location $root
$keystoreDir  = Join-Path $root "android\app"
$keystorePath = Join-Path $keystoreDir "sosphere-release.jks"
$propsPath    = Join-Path $keystoreDir "keystore.properties"

Write-Host ""
Write-Host "===================================================================="
Write-Host "  SOSphere - Release Keystore Generator"
Write-Host "===================================================================="
Write-Host ""

# 1. Check for keytool
$keytool = Get-Command keytool -ErrorAction SilentlyContinue
if (-not $keytool) {
    Write-Host "X  keytool not found. Install JDK 17 and re-run." -ForegroundColor Red
    Write-Host "   winget install EclipseAdoptium.Temurin.17.JDK"
    Write-Host "   or: choco install temurin17"
    exit 1
}

# 2. Refuse to overwrite
if (Test-Path $keystorePath) {
    Write-Host "!  A keystore already exists at:" -ForegroundColor Yellow
    Write-Host "     $keystorePath"
    Write-Host ""
    Write-Host "   Overwriting it would permanently lock you out of updating"
    Write-Host "   the app on Google Play. If you really want a fresh keystore:"
    Write-Host "     1. BACK UP the existing one first."
    Write-Host "     2. Delete it manually."
    Write-Host "     3. Re-run this script."
    exit 1
}

# 3. Prompt for password
Write-Host "You'll be asked to create a password for the keystore."
Write-Host "Rules: 8+ characters, use a password manager, write it down."
Write-Host ""

$ksPass1 = Read-Host "Keystore password" -AsSecureString
$ksPass2 = Read-Host "Confirm password " -AsSecureString

$ksPassPlain1 = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto(
    [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($ksPass1))
$ksPassPlain2 = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto(
    [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($ksPass2))

if ($ksPassPlain1 -ne $ksPassPlain2) {
    Write-Host "X  Passwords do not match. Aborting." -ForegroundColor Red
    exit 1
}
if ($ksPassPlain1.Length -lt 8) {
    Write-Host "X  Password must be at least 8 characters. Aborting." -ForegroundColor Red
    exit 1
}

# 4. Certificate Distinguished Name fields
$cn = if ($env:SOSPHERE_CERT_CN) { $env:SOSPHERE_CERT_CN } else { "SOSphere Safety Platform" }
$o  = if ($env:SOSPHERE_CERT_O)  { $env:SOSPHERE_CERT_O }  else { "SOSphere" }
$ou = if ($env:SOSPHERE_CERT_OU) { $env:SOSPHERE_CERT_OU } else { "Mobile" }
$l  = if ($env:SOSPHERE_CERT_L)  { $env:SOSPHERE_CERT_L }  else { "Riyadh" }
$st = if ($env:SOSPHERE_CERT_ST) { $env:SOSPHERE_CERT_ST } else { "Riyadh" }
$c  = if ($env:SOSPHERE_CERT_C)  { $env:SOSPHERE_CERT_C }  else { "SA" }
$alias = "sosphere"

Write-Host ""
Write-Host "Certificate details (press Enter to accept defaults):"
$input = Read-Host "  Common Name [$cn]"
if ($input) { $cn = $input }
$input = Read-Host "  Organization [$o]"
if ($input) { $o  = $input }
$input = Read-Host "  Country [$c]"
if ($input) { $c  = $input }

# 5. Generate keystore
New-Item -ItemType Directory -Force -Path $keystoreDir | Out-Null
$dname = "CN=$cn, OU=$ou, O=$o, L=$l, ST=$st, C=$c"

& keytool -genkeypair `
    -v `
    -keystore $keystorePath `
    -alias $alias `
    -keyalg RSA `
    -keysize 2048 `
    -validity 10950 `
    -storetype JKS `
    -storepass $ksPassPlain1 `
    -keypass $ksPassPlain1 `
    -dname $dname

if ($LASTEXITCODE -ne 0) {
    Write-Host "X  keytool failed (exit code $LASTEXITCODE). See output above." -ForegroundColor Red
    exit 1
}

Write-Host ""
Write-Host "OK  Keystore generated: $keystorePath" -ForegroundColor Green

# 6. Write keystore.properties
$propsContent = @"
# SOSphere release signing - generated by scripts/release-signing.ps1
# DO NOT COMMIT. This file is already gitignored.
storeFile=sosphere-release.jks
storePassword=$ksPassPlain1
keyAlias=$alias
keyPassword=$ksPassPlain1
"@

Set-Content -Path $propsPath -Value $propsContent

Write-Host "OK  keystore.properties written: $propsPath" -ForegroundColor Green
Write-Host ""
Write-Host "===================================================================="
Write-Host "  BACK UP NOW - this is a one-chance thing"
Write-Host "===================================================================="
Write-Host ""
Write-Host "  1. Copy $keystorePath to:"
Write-Host "       * A password manager vault attachment"
Write-Host "       * An encrypted offline drive"
Write-Host "       * A trusted cloud drive with 2FA enabled"
Write-Host ""
Write-Host "  2. Write the password down separately from the file."
Write-Host ""
Write-Host "  3. If you lose this file OR forget this password, you will NEVER"
Write-Host "     be able to update the app on Google Play."
Write-Host ""
Write-Host "===================================================================="
Write-Host "  Build a signed release APK now:"
Write-Host "     cd android ; .\gradlew assembleRelease"
Write-Host ""
Write-Host "  Build an Android App Bundle for Play Store:"
Write-Host "     cd android ; .\gradlew bundleRelease"
Write-Host "===================================================================="
